### ISSUE TITLE
Configuration de l'auditing

### ISSUE THREAD

**Issue by MentalistHB** [MentalistHB/Ambacam2018SpecTec#2]

**Comment by Coccoonx** [comment]
Adding JPA Auditing feature.
Auditing in a business application gives a way to track and log every single change in the database.
To implement it here, I followed these links:

https://dzone.com/articles/spring-data-jpa-auditing-automatically-the-good-stuff

and

https://dzone.com/articles/jpa-auditing-automatically-persisting-audit-logs
